"""Small transparent glossary used for offline smoke tests and term extraction."""

from __future__ import annotations

import re


ELECTRICIAN_GLOSSARIES: dict[str, dict[str, str]] = {
    "hin_Deva": {
        "ac supply": "एसी आपूर्ति",
        "ammeter": "अमीटर",
        "apprentice": "प्रशिक्षु",
        "cable": "केबल",
        "capacitor": "संधारित्र",
        "circuit breaker": "सर्किट ब्रेकर",
        "conduit": "कंड्यूट",
        "control panel": "नियंत्रण पैनल",
        "copper conductor": "तांबा चालक",
        "earthing": "अर्थिंग",
        "electric shock": "बिजली का झटका",
        "electrical load": "विद्युत भार",
        "fuse": "फ्यूज",
        "insulation": "इन्सुलेशन",
        "junction box": "जंक्शन बॉक्स",
        "leakage current": "लीकेज करंट",
        "live wire": "लाइव तार",
        "main switch": "मुख्य स्विच",
        "megger": "मेगर",
        "motor winding": "मोटर वाइंडिंग",
        "neutral wire": "न्यूट्रल तार",
        "phase tester": "फेज टेस्टर",
        "protective device": "सुरक्षा उपकरण",
        "resistance": "प्रतिरोध",
        "safety shoes": "सुरक्षा जूते",
        "single phase": "सिंगल फेज",
        "switch board": "स्विच बोर्ड",
        "terminal block": "टर्मिनल ब्लॉक",
        "three phase": "थ्री फेज",
        "voltage": "वोल्टेज",
        "voltmeter": "वोल्टमीटर",
        "wire stripper": "वायर स्ट्रिपर",
    },
    "gom_Deva": {
        "ac supply": "एसी पुरवठो",
        "ammeter": "अमीटर",
        "apprentice": "प्रशिक्षु",
        "cable": "केबल",
        "capacitor": "कॅपॅसिटर",
        "circuit breaker": "सर्किट ब्रेकर",
        "conduit": "कंड्यूट",
        "control panel": "कंट्रोल पॅनल",
        "copper conductor": "तांब्याचो वाहक",
        "earthing": "अर्थिंग",
        "electric shock": "विजेचो धक्का",
        "electrical load": "विद्युत भार",
        "fuse": "फ्यूज",
        "insulation": "इन्सुलेशन",
        "junction box": "जंक्शन बॉक्स",
        "leakage current": "लीकेज करंट",
        "live wire": "लाइव वायर",
        "main switch": "मुखेल स्विच",
        "megger": "मेगर",
        "motor winding": "मोटर वाइंडिंग",
        "neutral wire": "न्यूट्रल वायर",
        "phase tester": "फेज टेस्टर",
        "protective device": "सुरक्षा उपकरण",
        "resistance": "प्रतिकार",
        "safety shoes": "सुरक्षा बूट",
        "single phase": "सिंगल फेज",
        "switch board": "स्विच बोर्ड",
        "terminal block": "टर्मिनल ब्लॉक",
        "three phase": "थ्री फेज",
        "voltage": "व्होल्टेज",
        "voltmeter": "व्होल्टमीटर",
        "wire stripper": "वायर स्ट्रिपर",
    },
    "mai_Deva": {
        "ac supply": "एसी आपूर्ति",
        "ammeter": "अमीटर",
        "apprentice": "प्रशिक्षु",
        "cable": "केबल",
        "capacitor": "कैपेसिटर",
        "circuit breaker": "सर्किट ब्रेकर",
        "conduit": "कंड्यूट",
        "control panel": "कंट्रोल पैनल",
        "copper conductor": "तांबा चालक",
        "earthing": "अर्थिंग",
        "electric shock": "बिजलीक झटका",
        "electrical load": "विद्युत भार",
        "fuse": "फ्यूज",
        "insulation": "इन्सुलेशन",
        "junction box": "जंक्शन बॉक्स",
        "leakage current": "लीकेज करंट",
        "live wire": "लाइव तार",
        "main switch": "मुख्य स्विच",
        "megger": "मेगर",
        "motor winding": "मोटर वाइंडिंग",
        "neutral wire": "न्यूट्रल तार",
        "phase tester": "फेज टेस्टर",
        "protective device": "सुरक्षा उपकरण",
        "resistance": "प्रतिरोध",
        "safety shoes": "सुरक्षा जूता",
        "single phase": "सिंगल फेज",
        "switch board": "स्विच बोर्ड",
        "terminal block": "टर्मिनल ब्लॉक",
        "three phase": "थ्री फेज",
        "voltage": "वोल्टेज",
        "voltmeter": "वोल्टमीटर",
        "wire stripper": "वायर स्ट्रिपर",
    },
    "doi_Deva": {
        "ac supply": "एसी सप्लाई",
        "ammeter": "अमीटर",
        "apprentice": "प्रशिक्षु",
        "cable": "केबल",
        "capacitor": "कैपेसिटर",
        "circuit breaker": "सर्किट ब्रेकर",
        "conduit": "कंड्यूट",
        "control panel": "कंट्रोल पैनल",
        "copper conductor": "तांबे दा चालक",
        "earthing": "अर्थिंग",
        "electric shock": "बिजली दा झटका",
        "electrical load": "विद्युत भार",
        "fuse": "फ्यूज",
        "insulation": "इन्सुलेशन",
        "junction box": "जंक्शन बॉक्स",
        "leakage current": "लीकेज करंट",
        "live wire": "लाइव तार",
        "main switch": "मुख्य स्विच",
        "megger": "मेगर",
        "motor winding": "मोटर वाइंडिंग",
        "neutral wire": "न्यूट्रल तार",
        "phase tester": "फेज टेस्टर",
        "protective device": "सुरक्षा उपकरण",
        "resistance": "प्रतिरोध",
        "safety shoes": "सुरक्षा जूते",
        "single phase": "सिंगल फेज",
        "switch board": "स्विच बोर्ड",
        "terminal block": "टर्मिनल ब्लॉक",
        "three phase": "थ्री फेज",
        "voltage": "वोल्टेज",
        "voltmeter": "वोल्टमीटर",
        "wire stripper": "वायर स्ट्रिपर",
    },
}


def glossary_translate(text: str, target_lang: str) -> str:
    """Return a deterministic glossary-substitution translation hint."""
    glossary = ELECTRICIAN_GLOSSARIES.get(target_lang, ELECTRICIAN_GLOSSARIES["hin_Deva"])
    translated = text
    for english, target in sorted(glossary.items(), key=lambda item: len(item[0]), reverse=True):
        translated = re.sub(rf"\b{re.escape(english)}\b", target, translated, flags=re.IGNORECASE)
    return f"[fallback:{target_lang}] {translated}"
